import { useState } from "react";
import { useCreate, useList } from "@refinedev/core";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  ArrowRight,
  BookCopy,
  CheckCircle2,
  FileText,
  Settings2,
  Sparkles,
  Users,
  Wand2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { PositionSelector } from "./components/PositionSelector";
import { QuestionSelector } from "./components/QuestionSelector";
import { StudentSelector } from "./components/StudentSelector";
import type { IQuestion, IQuestionBank } from "@/types";
import {
  DEFAULT_NOTES,
  getErrorMessage,
  type ExamFormValues as ExamForm,
  validateExamForm,
} from "./components/exam-form-utils";

type StepId = "basic" | "questions" | "students" | "settings";
type QuestionMode = "manual" | "auto";

const initialForm: ExamForm = {
  title: "",
  description: "",
  start_time: "",
  end_time: "",
  duration_minutes: 60,
  total_score: 100,
  status: "draft",
  position_id: null,
  max_switch_count: 0,
  show_result: false,
  notes_template: "",
  question_ids: [],
  student_ids: [],
};

const stepItems: {
  id: StepId;
  title: string;
  description: string;
  icon: typeof FileText;
}[] = [
  {
    id: "basic",
    title: "基本信息",
    description: "先确定考试名称、时间与基础属性",
    icon: FileText,
  },
  {
    id: "questions",
    title: "选择题目",
    description: "支持手动选题或按条件自动出卷",
    icon: BookCopy,
  },
  {
    id: "students",
    title: "选择考生",
    description: "这一步可跳过，后续仍可补充考生",
    icon: Users,
  },
  {
    id: "settings",
    title: "考试设置",
    description: "最后确认切屏、结果展示与注意事项",
    icon: Settings2,
  },
];

const difficultyOptions = [
  { value: 1, label: "容易" },
  { value: 2, label: "较易" },
  { value: 3, label: "一般" },
  { value: 4, label: "较难" },
  { value: 5, label: "很难" },
];

const ALL_BANKS = "__all_banks__";

function shuffleQuestionIds(questions: IQuestion[], count: number): IQuestion[] {
  const next = [...questions];
  for (let i = next.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [next[i], next[j]] = [next[j], next[i]];
  }
  return next.slice(0, count);
}

export function ExamCreate() {
  const navigate = useNavigate();
  const { mutate: create, mutation } = useCreate();
  const isPending = mutation.isPending;

  const [form, setForm] = useState<ExamForm>(initialForm);
  const [currentStep, setCurrentStep] = useState(0);
  const [maxVisitedStep, setMaxVisitedStep] = useState(0);
  const [questionMode, setQuestionMode] = useState<QuestionMode>("manual");
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [flowError, setFlowError] = useState<string | null>(null);
  const [showValidationErrors, setShowValidationErrors] = useState(false);
  const [autoQuestionBankId, setAutoQuestionBankId] = useState<string | null>(null);
  const [autoQuestionCount, setAutoQuestionCount] = useState(10);
  const [autoDifficulties, setAutoDifficulties] = useState<number[]>([2, 3, 4]);
  const [autoGeneratedMeta, setAutoGeneratedMeta] = useState<{
    count: number;
    totalScore: number;
  } | null>(null);

  const validationErrors = validateExamForm(form);
  const fieldErrors = showValidationErrors ? validationErrors : {};

  const { query: questionBankQuery } = useList<IQuestionBank>({
    resource: "question-banks",
    pagination: { currentPage: 1, pageSize: 200 },
  });
  const questionBanks = questionBankQuery.data?.data ?? [];

  const { query: autoQuestionQuery } = useList<IQuestion>({
    resource: "questions",
    pagination: { currentPage: 1, pageSize: 500, mode: "server" },
    sorters: [{ field: "created_at", order: "desc" }],
    filters: [
      ...(autoQuestionBankId
        ? [{ field: "question_bank_id", operator: "eq" as const, value: autoQuestionBankId }]
        : []),
      ...(autoDifficulties.length > 0
        ? [{ field: "difficulty", operator: "in" as const, value: autoDifficulties }]
        : []),
    ],
    queryOptions: { enabled: questionMode === "auto" && currentStep === 1 },
  });
  const autoCandidates = autoQuestionQuery.data?.data ?? [];
  const autoCandidateTotal = autoQuestionQuery.data?.total ?? 0;
  const autoCandidateScore = autoCandidates.reduce((sum, question) => sum + question.score, 0);

  const updateField = <K extends keyof ExamForm>(key: K, value: ExamForm[K]) => {
    setForm((prev) => ({ ...prev, [key]: value }));
  };

  const markStepVisited = (stepIndex: number) => {
    setCurrentStep(stepIndex);
    setMaxVisitedStep((prev) => Math.max(prev, stepIndex));
  };

  const goNext = () => {
    setFlowError(null);

    if (currentStep === 0) {
      setShowValidationErrors(true);
      if (Object.keys(validationErrors).length > 0) {
        setFlowError("请先补全基本信息中的必填项。");
        return;
      }
    }

    if (currentStep === 1 && form.question_ids.length === 0) {
      setFlowError("请先手动选择题目，或使用自动出卷生成题单。");
      return;
    }

    if (currentStep < stepItems.length - 1) {
      markStepVisited(currentStep + 1);
    }
  };

  const goPrev = () => {
    setFlowError(null);
    if (currentStep > 0) {
      setCurrentStep((prev) => prev - 1);
    }
  };

  const handleAutoDifficultyChange = (level: number, checked: boolean) => {
    setAutoDifficulties((prev) => {
      if (checked) {
        return prev.includes(level) ? prev : [...prev, level].sort((a, b) => a - b);
      }
      return prev.filter((item) => item !== level);
    });
  };

  const handleAutoGenerate = () => {
    setFlowError(null);
    setAutoGeneratedMeta(null);

    if (autoDifficulties.length === 0) {
      setFlowError("自动出卷至少需要选择一个难度范围。");
      return;
    }

    if (!Number.isFinite(autoQuestionCount) || autoQuestionCount <= 0) {
      setFlowError("请填写有效的出题数量。");
      return;
    }

    if (autoCandidates.length < autoQuestionCount) {
      setFlowError(`当前条件下只有 ${autoCandidates.length} 道题，无法生成 ${autoQuestionCount} 道试题。`);
      return;
    }

    const picked = shuffleQuestionIds(autoCandidates, autoQuestionCount);
    updateField(
      "question_ids",
      picked.map((question) => question.id),
    );
    setAutoGeneratedMeta({
      count: picked.length,
      totalScore: picked.reduce((sum, question) => sum + question.score, 0),
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setShowValidationErrors(true);
    setSubmitError(null);
    setFlowError(null);

    if (Object.keys(validationErrors).length > 0) {
      setFlowError("请先修正表单中的错误信息后再创建考试。");
      return;
    }

    if (form.question_ids.length === 0) {
      setCurrentStep(1);
      setFlowError("创建考试前必须先选择题目。");
      return;
    }

    create(
      {
        resource: "exams",
        values: {
          ...form,
          start_time: form.start_time || null,
          end_time: form.end_time || null,
          notes_template: form.notes_template || null,
          position_id: form.position_id || null,
        },
      },
      {
        onSuccess: () => navigate("/exams"),
        onError: (error) => {
          setSubmitError(getErrorMessage(error, "创建考试失败，请稍后重试。"));
        },
      },
    );
  };

  const currentStepId = stepItems[currentStep].id;
  const selectedDifficultyLabels = difficultyOptions
    .filter((item) => autoDifficulties.includes(item.value))
    .map((item) => item.label);
  const summaryItems = [
    { label: "已选题目", value: `${form.question_ids.length} 题` },
    { label: "已选考生", value: `${form.student_ids.length} 人` },
    { label: "考试时长", value: `${form.duration_minutes} 分钟` },
    { label: "总分", value: `${form.total_score} 分` },
  ];

  return (
    <form className="space-y-6" onSubmit={handleSubmit}>
      <div className="flex items-center gap-3">
        <Button
          type="button"
          variant="ghost"
          size="sm"
          aria-label="返回考试列表"
          onClick={() => navigate("/exams")}
        >
          <ArrowLeft size={16} />
        </Button>
        <div className="min-w-0">
          <h1 className="text-base font-bold text-foreground tracking-tight">创建考试</h1>
          <p className="text-sm text-muted-foreground">
            按步骤完成信息填写、组卷、选人和设置，最后一次性创建考试。
          </p>
        </div>
      </div>

      {(submitError || flowError) && (
        <div
          className="rounded-lg border border-destructive/20 bg-destructive/10 p-3 text-sm text-destructive"
          role="alert"
        >
          {submitError ?? flowError}
        </div>
      )}

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
        <div className="space-y-6">
          <Card>
            <CardContent className="space-y-3 pt-6">
              <div className="grid gap-3 md:grid-cols-4">
                {stepItems.map((step, index) => {
                  const Icon = step.icon;
                  const isActive = index === currentStep;
                  const isDone = index < currentStep;
                  const isClickable = index <= maxVisitedStep;

                  return (
                    <button
                      key={step.id}
                      type="button"
                      disabled={!isClickable}
                      onClick={() => {
                        if (isClickable) {
                          setFlowError(null);
                          setCurrentStep(index);
                        }
                      }}
                      className={`rounded-xl border p-4 text-left transition-colors ${
                        isActive
                          ? "border-primary bg-primary/5"
                          : isDone
                            ? "border-emerald-500/25 bg-emerald-500/5"
                            : "border-border bg-background"
                      } ${isClickable ? "cursor-pointer" : "cursor-not-allowed opacity-60"}`}
                    >
                      <div className="mb-3 flex items-center justify-between">
                        <span
                          className={`flex h-8 w-8 items-center justify-center rounded-full border text-sm font-semibold ${
                            isActive
                              ? "border-primary bg-primary text-primary-foreground"
                              : isDone
                                ? "border-emerald-600 bg-emerald-600 text-white"
                                : "border-border bg-muted text-muted-foreground"
                          }`}
                        >
                          {isDone ? <CheckCircle2 size={16} /> : index + 1}
                        </span>
                        <Icon size={16} className={isActive ? "text-primary" : "text-muted-foreground"} />
                      </div>
                      <p className="text-sm font-semibold text-foreground">{step.title}</p>
                      <p className="mt-1 text-xs leading-5 text-muted-foreground">{step.description}</p>
                    </button>
                  );
                })}
              </div>
            </CardContent>
          </Card>

          {currentStepId === "basic" && (
            <Card>
              <CardHeader>
                <CardTitle>第 1 步：填写基本信息</CardTitle>
              </CardHeader>
              <CardContent className="space-y-5">
                <div className="space-y-1.5">
                  <Label htmlFor="exam-title">考试名称 *</Label>
                  <Input
                    id="exam-title"
                    placeholder="例如：Java 后端岗位笔试"
                    value={form.title}
                    onChange={(e) => updateField("title", e.target.value)}
                    aria-invalid={Boolean(fieldErrors.title)}
                    aria-describedby={fieldErrors.title ? "exam-title-error" : undefined}
                    autoFocus
                  />
                  {fieldErrors.title && (
                    <p id="exam-title-error" className="text-xs text-destructive">
                      {fieldErrors.title}
                    </p>
                  )}
                </div>

                <div className="space-y-1.5">
                  <Label htmlFor="exam-description">考试描述</Label>
                  <Textarea
                    id="exam-description"
                    placeholder="给教师或考生补充一些背景说明（可选）"
                    value={form.description}
                    onChange={(e) => updateField("description", e.target.value)}
                    rows={3}
                  />
                </div>

                <div className="space-y-1.5">
                  <Label htmlFor="exam-position">岗位</Label>
                  <PositionSelector
                    id="exam-position"
                    value={form.position_id}
                    onChange={(id) => updateField("position_id", id)}
                  />
                </div>

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div className="space-y-1.5">
                    <Label htmlFor="exam-start-time">开始时间</Label>
                    <Input
                      id="exam-start-time"
                      type="datetime-local"
                      value={form.start_time}
                      onChange={(e) => updateField("start_time", e.target.value)}
                      aria-invalid={Boolean(fieldErrors.start_time)}
                      aria-describedby={fieldErrors.start_time ? "exam-start-time-error" : undefined}
                    />
                    {fieldErrors.start_time && (
                      <p id="exam-start-time-error" className="text-xs text-destructive">
                        {fieldErrors.start_time}
                      </p>
                    )}
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="exam-end-time">结束时间</Label>
                    <Input
                      id="exam-end-time"
                      type="datetime-local"
                      value={form.end_time}
                      onChange={(e) => updateField("end_time", e.target.value)}
                      aria-invalid={Boolean(fieldErrors.end_time)}
                      aria-describedby={fieldErrors.end_time ? "exam-end-time-error" : undefined}
                    />
                    {fieldErrors.end_time && (
                      <p id="exam-end-time-error" className="text-xs text-destructive">
                        {fieldErrors.end_time}
                      </p>
                    )}
                  </div>
                </div>

                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <div className="space-y-1.5">
                    <Label htmlFor="exam-duration">考试时长（分钟）</Label>
                    <Input
                      id="exam-duration"
                      type="number"
                      min={1}
                      value={form.duration_minutes}
                      onChange={(e) =>
                        updateField("duration_minutes", parseInt(e.target.value, 10) || 60)
                      }
                      aria-invalid={Boolean(fieldErrors.duration_minutes)}
                      aria-describedby={fieldErrors.duration_minutes ? "exam-duration-error" : undefined}
                    />
                    {fieldErrors.duration_minutes && (
                      <p id="exam-duration-error" className="text-xs text-destructive">
                        {fieldErrors.duration_minutes}
                      </p>
                    )}
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="exam-total-score">总分</Label>
                    <Input
                      id="exam-total-score"
                      type="number"
                      min={1}
                      value={form.total_score}
                      onChange={(e) =>
                        updateField("total_score", parseFloat(e.target.value) || 100)
                      }
                      aria-invalid={Boolean(fieldErrors.total_score)}
                      aria-describedby={fieldErrors.total_score ? "exam-total-score-error" : undefined}
                    />
                    {fieldErrors.total_score && (
                      <p id="exam-total-score-error" className="text-xs text-destructive">
                        {fieldErrors.total_score}
                      </p>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {currentStepId === "questions" && (
            <Card>
              <CardHeader>
                <CardTitle>第 2 步：选择题目 / 自动出卷</CardTitle>
                <CardDescription>你可以直接手动挑题，也可以按题库和难度快速生成题单。</CardDescription>
              </CardHeader>
              <CardContent className="space-y-5">
                <div className="grid gap-3 md:grid-cols-2">
                  <button
                    type="button"
                    onClick={() => {
                      setQuestionMode("manual");
                      setFlowError(null);
                    }}
                    className={`rounded-xl border p-4 text-left transition-colors ${
                      questionMode === "manual" ? "border-primary bg-primary/5" : "border-border bg-background"
                    }`}
                  >
                    <div className="mb-3 flex items-center gap-2">
                      <BookCopy size={16} className={questionMode === "manual" ? "text-primary" : "text-muted-foreground"} />
                      <p className="text-sm font-semibold text-foreground">手动选题</p>
                    </div>
                    <p className="text-xs leading-5 text-muted-foreground">
                      适合精确控制题目内容、题型和顺序。
                    </p>
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setQuestionMode("auto");
                      setFlowError(null);
                    }}
                    className={`rounded-xl border p-4 text-left transition-colors ${
                      questionMode === "auto" ? "border-primary bg-primary/5" : "border-border bg-background"
                    }`}
                  >
                    <div className="mb-3 flex items-center gap-2">
                      <Wand2 size={16} className={questionMode === "auto" ? "text-primary" : "text-muted-foreground"} />
                      <p className="text-sm font-semibold text-foreground">自动出卷</p>
                    </div>
                    <p className="text-xs leading-5 text-muted-foreground">
                      按题库、数量和难度随机抽题，快速生成第一版题单。
                    </p>
                  </button>
                </div>

                <div className="rounded-xl border border-border/80 bg-muted/30 p-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge variant="outline">当前已选 {form.question_ids.length} 题</Badge>
                    {autoGeneratedMeta && (
                      <Badge variant="secondary">
                        最近一次自动生成 {autoGeneratedMeta.count} 题 / {autoGeneratedMeta.totalScore} 分
                      </Badge>
                    )}
                  </div>
                </div>

                {questionMode === "manual" ? (
                  <QuestionSelector
                    selectedIds={form.question_ids}
                    onChange={(ids) => {
                      updateField("question_ids", ids);
                      setAutoGeneratedMeta(null);
                    }}
                  />
                ) : (
                  <div className="space-y-5">
                    <div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_140px]">
                      <div className="space-y-1.5">
                        <Label htmlFor="auto-question-bank">题库范围</Label>
                        <Select
                          value={autoQuestionBankId ?? ALL_BANKS}
                          onValueChange={(value) =>
                            setAutoQuestionBankId(value === ALL_BANKS ? null : value)
                          }
                        >
                          <SelectTrigger id="auto-question-bank">
                            <SelectValue placeholder="全部题库" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value={ALL_BANKS}>全部题库</SelectItem>
                            {questionBanks.map((bank) => (
                              <SelectItem key={bank.id} value={bank.id}>
                                {bank.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="space-y-1.5">
                        <Label htmlFor="auto-question-count">出题数量</Label>
                        <Input
                          id="auto-question-count"
                          type="number"
                          min={1}
                          value={autoQuestionCount}
                          onChange={(e) => setAutoQuestionCount(parseInt(e.target.value, 10) || 0)}
                        />
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label>难度范围</Label>
                      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">
                        {difficultyOptions.map((item) => {
                          const checked = autoDifficulties.includes(item.value);
                          return (
                            <label
                              key={item.value}
                              className={`flex items-center gap-3 rounded-lg border px-3 py-2 text-sm transition-colors ${
                                checked ? "border-primary bg-primary/5" : "border-border bg-background"
                              }`}
                            >
                              <Checkbox
                                checked={checked}
                                onCheckedChange={(value) =>
                                  handleAutoDifficultyChange(item.value, value === true)
                                }
                              />
                              <span>{item.label}</span>
                            </label>
                          );
                        })}
                      </div>
                    </div>

                    <div className="grid gap-3 lg:grid-cols-3">
                      <div className="rounded-xl border border-border/80 bg-background p-4">
                        <p className="text-xs text-muted-foreground">候选题量</p>
                        <p className="mt-1 text-2xl font-semibold text-foreground">
                          {autoQuestionQuery.isLoading ? "加载中..." : `${autoCandidateTotal} 题`}
                        </p>
                      </div>
                      <div className="rounded-xl border border-border/80 bg-background p-4">
                        <p className="text-xs text-muted-foreground">候选总分</p>
                        <p className="mt-1 text-2xl font-semibold text-foreground">
                          {autoCandidateScore} 分
                        </p>
                      </div>
                      <div className="rounded-xl border border-border/80 bg-background p-4">
                        <p className="text-xs text-muted-foreground">当前难度</p>
                        <p className="mt-1 text-sm font-medium text-foreground">
                          {selectedDifficultyLabels.length > 0 ? selectedDifficultyLabels.join(" / ") : "未选择"}
                        </p>
                      </div>
                    </div>

                    <div className="flex flex-col gap-3 rounded-xl border border-border/80 bg-background p-4 sm:flex-row sm:items-center sm:justify-between">
                      <div>
                        <p className="text-sm font-semibold text-foreground">生成题单</p>
                        <p className="mt-1 text-xs text-muted-foreground">
                          满足条件后会随机抽题，并直接覆盖当前已选题目。
                        </p>
                      </div>
                      <Button
                        type="button"
                        onClick={handleAutoGenerate}
                        disabled={autoQuestionQuery.isLoading || autoQuestionCount <= 0}
                      >
                        <Sparkles size={16} className="mr-1" />
                        {autoGeneratedMeta ? "重新生成" : "生成题单"}
                      </Button>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {currentStepId === "students" && (
            <Card>
              <CardHeader>
                <CardTitle>第 3 步：选择考试考生</CardTitle>
                <CardDescription>
                  这一步是可选的。你可以现在绑定考生，也可以先建考试，稍后再补充。
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="rounded-xl border border-border/80 bg-muted/30 p-4 text-sm text-muted-foreground">
                  当前已选 <span className="font-semibold text-foreground">{form.student_ids.length}</span> 名考生。
                  如果暂时不选，后续在编辑考试时仍可继续添加。
                </div>
                <StudentSelector
                  selectedIds={form.student_ids}
                  onChange={(ids) => updateField("student_ids", ids)}
                />
              </CardContent>
            </Card>
          )}

          {currentStepId === "settings" && (
            <Card>
              <CardHeader>
                <CardTitle>第 4 步：考试设置</CardTitle>
                <CardDescription>最后确认切屏限制、结果展示和给考生的说明文字。</CardDescription>
              </CardHeader>
              <CardContent className="space-y-5">
                <div className="grid gap-3 rounded-xl border border-border/80 bg-muted/30 p-4 md:grid-cols-4">
                  {summaryItems.map((item) => (
                    <div key={item.label}>
                      <p className="text-xs text-muted-foreground">{item.label}</p>
                      <p className="mt-1 text-sm font-semibold text-foreground">{item.value}</p>
                    </div>
                  ))}
                </div>

                <div className="space-y-1.5">
                  <Label htmlFor="exam-max-switch-count">允许切屏次数</Label>
                  <Input
                    id="exam-max-switch-count"
                    type="number"
                    min={0}
                    value={form.max_switch_count}
                    onChange={(e) =>
                      updateField("max_switch_count", parseInt(e.target.value, 10) || 0)
                    }
                    aria-invalid={Boolean(fieldErrors.max_switch_count)}
                    aria-describedby="exam-max-switch-count-help"
                  />
                  <p id="exam-max-switch-count-help" className="text-xs text-muted-foreground">
                    设为 0 表示不限制切屏次数。
                  </p>
                  {fieldErrors.max_switch_count && (
                    <p className="text-xs text-destructive">{fieldErrors.max_switch_count}</p>
                  )}
                </div>

                <div className="flex flex-col gap-3 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between">
                  <div>
                    <Label htmlFor="exam-show-result">允许查看考试结果</Label>
                    <p className="mt-0.5 text-xs text-muted-foreground">
                      考生提交后是否可以查看批改结果详情。
                    </p>
                  </div>
                  <Switch
                    id="exam-show-result"
                    checked={form.show_result}
                    onCheckedChange={(checked) => updateField("show_result", checked)}
                  />
                </div>

                <div className="space-y-1.5">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="exam-notes">考试注意事项</Label>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="h-8 text-xs"
                      onClick={() => updateField("notes_template", DEFAULT_NOTES)}
                    >
                      使用默认模板
                    </Button>
                  </div>
                  <Textarea
                    id="exam-notes"
                    placeholder="请输入考试注意事项..."
                    value={form.notes_template}
                    onChange={(e) => updateField("notes_template", e.target.value)}
                    rows={8}
                  />
                </div>
              </CardContent>
            </Card>
          )}

          <div className="flex flex-col gap-3 rounded-xl border border-border bg-background p-4 sm:flex-row sm:items-center sm:justify-between">
            <div className="text-sm text-muted-foreground">
              {currentStepId === "students"
                ? "考生选择是可选项。你可以直接继续到最后一步。"
                : stepItems[currentStep].description}
            </div>
            <div className="flex w-full flex-col-reverse gap-3 sm:w-auto sm:flex-row">
              <Button
                type="button"
                variant="outline"
                className="w-full sm:w-auto"
                onClick={goPrev}
                disabled={currentStep === 0}
              >
                上一步
              </Button>

              {currentStep < stepItems.length - 1 ? (
                <Button type="button" className="w-full sm:w-auto" onClick={goNext}>
                  {currentStepId === "students" && form.student_ids.length === 0 ? "跳过并继续" : "下一步"}
                  <ArrowRight size={16} className="ml-1" />
                </Button>
              ) : (
                <Button
                  type="submit"
                  className="w-full sm:w-auto"
                  disabled={!form.title.trim() || isPending}
                >
                  {isPending ? (
                    <span className="flex items-center gap-2">
                      <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />
                      创建中...
                    </span>
                  ) : (
                    "创建考试"
                  )}
                </Button>
              )}
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <Card className="xl:sticky xl:top-6">
            <CardHeader>
              <CardTitle className="text-base">摘要</CardTitle>
            </CardHeader>
            <CardContent className="space-y-5">
              <div className="space-y-2">
                <p className="text-xs text-muted-foreground">考试名称</p>
                <p className="text-sm font-semibold text-foreground">
                  {form.title.trim() || "未填写"}
                </p>
              </div>

              <Separator />

              <div className="space-y-3">
                {summaryItems.map((item) => (
                  <div key={item.label} className="flex items-center justify-between gap-3 text-sm">
                    <span className="text-muted-foreground">{item.label}</span>
                    <span className="font-medium text-foreground">{item.value}</span>
                  </div>
                ))}
              </div>

              <Separator />

              <div className="space-y-2">
                <p className="text-xs text-muted-foreground">组卷方式</p>
                <div className="flex flex-wrap gap-2">
                  <Badge variant={questionMode === "manual" ? "secondary" : "outline"}>
                    {questionMode === "manual" ? "手动选题" : "自动出卷"}
                  </Badge>
                  {questionMode === "auto" && autoGeneratedMeta && (
                    <Badge variant="outline">
                      已自动生成 {autoGeneratedMeta.count} 题
                    </Badge>
                  )}
                </div>
              </div>

              {questionMode === "auto" && (
                <>
                  <Separator />
                  <div className="space-y-2">
                    <p className="text-xs text-muted-foreground">自动出卷条件</p>
                    <p className="text-sm text-foreground">
                      题库：{
                        autoQuestionBankId
                          ? questionBanks.find((bank) => bank.id === autoQuestionBankId)?.name ?? "已选题库"
                          : "全部题库"
                      }
                    </p>
                    <p className="text-sm text-foreground">数量：{autoQuestionCount} 题</p>
                    <p className="text-sm text-foreground">
                      难度：{selectedDifficultyLabels.length > 0 ? selectedDifficultyLabels.join(" / ") : "未选择"}
                    </p>
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </form>
  );
}
