const ROLE_CAPABILITIES: Record<string, ReadonlyArray<string>> = {
  platform_admin: ["*"],
  school_admin: [
    "exam.create",
    "exam.read",
    "exam.update",
    "exam.delete",
    "question.create",
    "question.read",
    "question.update",
    "question.delete",
    "course.create",
    "course.read",
    "course.update",
    "course.delete",
    "knowledge.create",
    "knowledge.read",
    "knowledge.update",
    "knowledge.delete",
    "user.create",
    "user.read",
    "user.update",
    "job_model.read",
    "gap_analysis.create",
    "gap_analysis.read",
    "export.create",
  ],
  enterprise_admin: [
    "exam.create",
    "exam.read",
    "exam.update",
    "exam.delete",
    "question.create",
    "question.read",
    "question.update",
    "question.delete",
    "knowledge.read",
    "job_model.create",
    "job_model.read",
    "job_model.update",
    "job_model.delete",
    "user.create",
    "user.read",
    "user.update",
    "gap_analysis.read",
    "export.create",
  ],
  enterprise_user: ["job_model.read", "job_model.update", "export.create"],
  teacher: [
    "exam.create",
    "exam.read",
    "exam.update",
    "question.create",
    "question.read",
    "question.update",
    "course.read",
    "course.update",
    "knowledge.read",
    "job_model.read",
    "gap_analysis.read",
    "export.create",
  ],
  evaluator: [
    "exam.create",
    "exam.read",
    "exam.update",
    "question.create",
    "question.read",
    "question.update",
    "course.read",
    "course.update",
    "knowledge.read",
    "job_model.read",
    "gap_analysis.read",
    "export.create",
  ],
  student: ["exam.read", "course.read", "knowledge.read"],
  assessee: ["exam.read", "course.read", "knowledge.read"],
};

export function userHasCapability(roles: ReadonlyArray<string>, capability: string): boolean {
  return roles.some((role) => {
    const capabilities = ROLE_CAPABILITIES[role];
    return Boolean(capabilities?.includes("*") || capabilities?.includes(capability));
  });
}
